### ISSUE TITLE
Unable to enable iOS and Snapshot

### ISSUE THREAD

**Issue by skoveng** [vultr/whmcs-vultr#65]
I don't get to turn on iOS or snapshot, I have no choice where it says enable.

What can this come from? I've been to the product and Generate default - Configurable Options And Custom Fields, but don't have the option to enable anything.

Is there anyone who can help me here?

**Comment by breakforme732** [comment]
Hello @skoveng 

I assume you're referring to the OS list and snapshot list? Please provide more information about this including the versions you are using and and example of steps to reproduce this issue.

**Comment by thehostingteam** [comment]
HEY this is a HUGE ISSUE not being able to select ios and snapshots.... ive been waiting 4 days now myself and no progress i am pretty bummed about this i own thehostingteam ucanhost and https://hostio.site but i have customers bi***ing at me because they cant edit these settings and im losing money because of this its not as simple as reading the docs because i have done this many times and gone over your code but im confused myself as what is going on here as it is not my project please let me know asap what is going on or if it does work please get a hold of me at https;//tawk.to/stormmoran and leave me a message on how to get back to you i will give access to server so you can see what i am talking about first hand

**Comment by breakforme732** [comment]
Hello @thehostingteam 
I would need you to provide me with the versions you are using and the steps to reproduce this issue to be able to help you with this.

**Comment by thehostingteam** [comment]
@breakforme732 hello so all i am doing is Working from a fresh install of whmcs 7.9.1 on a fresh cpanel&whm server on google cloud i then goto https://www.vultr.com/docs/vultr-whmcs-module and follow every STEP i would be using the master as i thought this is the most up todate version of this plugin so with this being said after install plugin(addon) i go in as myself under my cpanel store @ https://hostio.site and try to purchase the server for real money even and i tried free and other versions of payment to get it to work with no luck i am willing to give access to my server to better help but if so please contact me @ https://tawk.to/stormmoran and at the bottom right please let me know its breakforme732 and please feel free to use a vpn for security if you have one if not i will have your chat and ip deleted from my tawk.to records but i will be on 24/7 waiting for your reply drinking alot of coffee!!!!

**Comment by breakforme732** [comment]
Hello @thehostingteam 
Please ensure that your Vultr account API key is entered correctly. Please also ensure that you have configured your options properly
