### ISSUE TITLE
[BUG] - Select OS Type

### ISSUE THREAD

**Issue by ThiagoPecorari** [vultr/whmcs-vultr#67]
The operating system cannot be selected, it is not shown in the drop-down list and the consequence is that the VPS is not created in the vultr.

![image](https://user-images.githubusercontent.com/48068393/72942790-232db780-3d53-11ea-8e9d-b2b74f2441ad.png)

![image](https://user-images.githubusercontent.com/48068393/72942825-38a2e180-3d53-11ea-9c86-747c1ee5bae0.png)

**Comment by breakforme732** [comment]
Hello @ThiagoPecorari 
You have to configure the options to get options in the dropdown. Please be sure to follow the documentation for the module.

**Comment by thehostingteam** [comment]
hey can someone get back to be on this please im still seeing the same as person above on front end and backend of cpanel&whm my site can be located @ https://hostio.site please :( ive been waiting and waiting and i have customers complaining with me because i shut our vps service down till its fixed
